<?php

namespace App\Support;

class BlogArticles
{
    public static function all(): array
    {
        return [
            [
                'id' => 1,
                'featured' => true,
                'status' => 'published',
                'slug' => 'rise-of-regional-hubs',
                'title' => 'The Rise of Regional Hubs: How Distributed Teams are Redefining Productivity',
                'excerpt' => 'As major tech giants shift towards flexible models, regional workspace hubs are emerging as the new centers of innovation.',
                'category' => 'Workspace Trends',
                'category_slug' => 'workspace-trends',
                'read_time' => 12,
                'date' => 'May 18, 2024',
                'updated_at' => '2024-05-18',
                'views' => 1240,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuC7BZMvaIc81CPJ7uEg3hJql8gg6QZISMc0znoER0Pu9TKyIUaD35UMjDtTKSpgw8-lIfD3Tcvj6LRUvEN-DVed6wv867VYF26P7T8qX3zsRV2xPdiiN2hYSgrxPr_ryLpckZ8LPLwv_zNdMJ3km_TvDZuZhcF13n3mEDzJjeGgV3WgS4fUCd0_XTuytzA7RCNIm6Rlji9qyOLKiQdklPyvXJgtIjc1EQHM77f6kx4-79eT-gMAYTKL0lbSXtEtl5g_QsTcVSPSWrw',
                'author_name' => 'James Danjuma',
            ],
            [
                'id' => 2,
                'featured' => false,
                'status' => 'published',
                'slug' => 'increase-booking-revenue',
                'title' => '5 Ways to Increase Your Booking Revenue as a Host',
                'excerpt' => 'From lighting upgrades to high-speed fiber internet, learn which amenities actually drive long-term bookings.',
                'category' => 'Hosting Tips',
                'category_slug' => 'hosting-tips',
                'read_time' => 5,
                'date' => 'May 15, 2024',
                'updated_at' => '2024-05-15',
                'views' => 890,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCttr6Mbat9xVadAlh5dbcyMoqK-7ZDJEENWMYJqSKeR1tuuEk987aIcUazosva8zTaU6j2l7IkQbGHEmVzF0aa5OsxBd9uKk0wk1jjkOUuL7oci51xHFUCzIz3_-hyb4TQzw1ERDzUiCytT_nBk6J0U11HMxfPNuVSuYfeLNU0MYtIlVeJxk7imNf7aynWb6F4I_XGPbCEUj42n_5eDsWrPofP3kUH8hAxT5GavVkM90r5HbjovD5zgrjStVuyILPFf3PZNGBZezs',
                'author_name' => 'GridSpace Team',
            ],
            [
                'id' => 3,
                'featured' => false,
                'status' => 'draft',
                'slug' => 'technova-member-spotlight',
                'title' => 'Member Spotlight: How TechNova Scaled via GridSpace',
                'excerpt' => 'A deep dive into how a small startup utilized on-demand meeting rooms and satellite offices.',
                'category' => 'Community Stories',
                'category_slug' => 'community-stories',
                'read_time' => 8,
                'date' => 'May 12, 2024',
                'updated_at' => '2024-05-12',
                'views' => 0,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuBTgW5KiXYpd8tCYpaWvkGl_XpB0-Ub3vkozQv1ko6q4Gy1Z-chKevEY1XJSUO5RsiuJGuM1fwxKEoLwR22wog-wlVFPPNGa-Mtw3a0b6hL1Rjw0Q7xjfJUEfNd2kgFgvwvaHjsBqMYHgRm9WBLuFcyNaYQ7rCAuCBENhu2qlVhyKK5rwRzBK8c89GWn7YsApOlIVp0G8WyC5lUYEV9ijWH2eEAH0HjUpEhkIajLhVHQ_rZkfBEwsLBQXh0JyPqnlJiFcBSGQ9Vi4U',
                'author_name' => 'GridSpace Team',
            ],
            [
                'id' => 4,
                'featured' => false,
                'status' => 'published',
                'slug' => '2025-hybrid-work-report',
                'title' => 'Beyond the Office: The 2025 Hybrid Work Report',
                'excerpt' => "Our latest research on where people are working and why 'Third Spaces' are becoming the preferred choice.",
                'category' => 'Future of Work',
                'category_slug' => 'future-of-work',
                'read_time' => 6,
                'date' => 'May 08, 2024',
                'updated_at' => '2024-05-08',
                'views' => 2100,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDZ86jLzzsfyLOcR5I576v9kqLtZTJhiUSFIi5GK1uX4vKoYDxUyOLx5KC6UkiTjnlyBkml-vG0aCpxeK1y0dEWbZQl-3kzPI6S_5VI2bWc-jAQzLBnGvafrPe45VuyMkjlBMmM5PnOcXg4cHQcYxdPMA0cPmam_UXvDqv5NvzFsOQVrPXsibH8nlBdDNStMhlqkTf6pmmCp8N9vYoKVTEcxSf4hdE_n3H0H2C_iF1FMW993wpbhJkQPd1Q5E8xUEIFxlKGU3hZu98',
                'author_name' => 'GridSpace Research',
            ],
            [
                'id' => 5,
                'featured' => false,
                'status' => 'published',
                'slug' => 'mastering-deep-work',
                'title' => 'Mastering Deep Work in Shared Spaces',
                'excerpt' => 'Practical strategies for maintaining high levels of focus and concentration while working in dynamic co-working environments.',
                'category' => 'Productivity',
                'category_slug' => 'workspace-trends',
                'read_time' => 4,
                'date' => 'May 05, 2024',
                'updated_at' => '2024-05-05',
                'views' => 560,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuApeBi6lDiMAEKbEx97t8Q13Tnm8W2t9NbphrrvBqYL6jesB7j1rANuFZwRn6zazoYayQz03yzh2g5dwoQVMNqpgW2tQt3_9dgWc2KD5uIdyFjY2czBKXXKN2iKjdOrQcN_G7FRM4s092y4Y1Xvq1aW4i2Wuf-6f9Sp1N7135uRhR7WQx30tkSGaPCBZ0h7xXG6zaYmy41ipuTN5NAdmPCleiuMYBInwLBDvDVme9e0qkYikkaim_c3ZP4cxWrUVOvIYxyuz0G_c1E',
                'author_name' => 'GridSpace Team',
            ],
            [
                'id' => 6,
                'featured' => false,
                'status' => 'published',
                'slug' => 'lighting-workspace-mood',
                'title' => 'How Lighting Affects Workspace Mood and Booking Rates',
                'excerpt' => 'Understanding the psychology of light in commercial spaces and how hosts can optimize their environments.',
                'category' => 'Design',
                'category_slug' => 'hosting-tips',
                'read_time' => 7,
                'date' => 'Apr 28, 2024',
                'updated_at' => '2024-04-28',
                'views' => 430,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuCxM_6nVk0U7YRKRn5nMEgTogi0BbtNdz9hsb0HSmkH95JMJW2gyJQg22_QGkJ1o5k_9UC3kXz-nz6tC0HFnYkF4B0D42uSG75zSz2r0-PPyYqYrCgWEZ3osT6yQPTGuIbF-QMVJIt_EeO1XqiN6fbAofFv6tq_i9LGg0RKlVqCeQ8E38G1EE3O2iVRIv3FFLYAk-Jv83pddJBzn7oipKAw5PpTwN2wV2H7VusRAAqfx3xe7Vfb7LUs6Ho0p3XWhFPGbBboDYXXACU',
                'author_name' => 'GridSpace Team',
            ],
            [
                'id' => 7,
                'featured' => false,
                'status' => 'published',
                'slug' => 'shared-culture-virtual-first',
                'title' => 'Building a Shared Culture in a Virtual-First World',
                'excerpt' => 'Experts share their advice on maintaining team cohesion when employees are spread across multiple workspaces.',
                'category' => 'Culture',
                'category_slug' => 'community-stories',
                'read_time' => 10,
                'date' => 'Apr 22, 2024',
                'updated_at' => '2024-04-22',
                'views' => 720,
                'image' => 'https://lh3.googleusercontent.com/aida-public/AB6AXuDluH2tj5B4_qfnFuA8k2S3nQF0ntKXIt13LEp0JkjYmiryO58-iwxumCgZtAKNq_FKpSmXz0nbBE5V2SHJu0Nd3L90vELWb_dV_dHCHrrMBmPs0GBjzbexwZ2dpkZps7Z3Wc-IPr2apMJMhsDwBtyI5eKK-hldzf-tqOGNSN3rmB70BTh-9JZdRduW_PeciitKEM_toeEEwHAxJ_7YZdJ2uMXTQ0jlv6jduttgFfXpcb4dCrtk8xl5w2hWL-6LRqtOb-eTvDCg2fA',
                'author_name' => 'GridSpace Team',
            ],
        ];
    }

    public static function categories(): array
    {
        return [
            'workspace-trends' => 'Workspace Trends',
            'hosting-tips' => 'Hosting Tips',
            'community-stories' => 'Community Stories',
            'future-of-work' => 'Future of Work',
        ];
    }
}
